import type { Metadata } from 'next'
import { ArrowRight, BadgeCheck, Ban, DatabaseZap, FileCheck2, Fingerprint, LockKeyhole, ScanSearch, ShieldCheck, WalletCards } from 'lucide-react'
import { MarketingShell } from '@/components/marketing/marketing-shell'

export const metadata: Metadata = {
  title: 'Trust & Safety | Erna',
  description: 'See how Erna protects task participation, proof review, wallets and account access.',
}

export default function TrustPage() {
  return <MarketingShell>
    <section className="trust-page-hero"><div className="page-container trust-hero-grid"><div><span className="eyebrow"><ShieldCheck size={15} /> Trust &amp; safety</span><h1>Protection should be part of the <span>flow, not a footnote.</span></h1><p>Erna is designed so that task instructions, proof, campaign funds and account actions leave a record. Clear states make problems easier to prevent and disputes easier to investigate.</p><a className="button button-light" href="/contact">Report a concern <ArrowRight size={18} /></a></div><div className="trust-signal" aria-label="Erna protection layers"><div className="signal-core"><LockKeyhole size={30} /><strong>Protected by design</strong><span>Identity • funds • proof • audit</span></div><span className="signal-ring signal-ring-one" /><span className="signal-ring signal-ring-two" /><div className="signal-tag signal-tag-one"><Fingerprint size={17} /> Account controls</div><div className="signal-tag signal-tag-two"><FileCheck2 size={17} /> Proof trail</div><div className="signal-tag signal-tag-three"><WalletCards size={17} /> Funded tasks</div></div></div></section>
    <section className="trust-proof-strip"><div className="page-container"><span><BadgeCheck size={18} /> No activation fee</span><span><LockKeyhole size={18} /> Funded before launch</span><span><ScanSearch size={18} /> Proof checked against instructions</span><span><DatabaseZap size={18} /> Wallet changes stay server-side</span></div></section>
    <section className="content-section protection-section"><div className="page-container"><div className="section-kicker protection-heading"><span className="eyebrow">Protection at every handoff</span><h2>One clear chain from campaign funding to worker payout.</h2></div><div className="protection-flow"><article><span>01</span><div><WalletCards size={22} /><h3>Funds first</h3><p>An advertiser funds the campaign before it can go live. Workers never start against an unfunded promise.</p></div></article><article><span>02</span><div><FileCheck2 size={22} /><h3>Proof in context</h3><p>Each submission is reviewed against the exact instructions shown before the worker began.</p></div></article><article><span>03</span><div><DatabaseZap size={22} /><h3>Server-led movement</h3><p>Wallet balances are not calculated or changed by the browser. Money events are processed and recorded server-side.</p></div></article><article><span>04</span><div><ScanSearch size={22} /><h3>Audit when needed</h3><p>Task decisions, wallet transactions and administrative actions keep a timestamped trail for investigation.</p></div></article></div></div></section>
    <section className="content-section trust-boundaries"><div className="page-container boundaries-grid"><div><span className="eyebrow"><Ban size={15} /> Clear boundaries</span><h2>What Erna is not.</h2><p>Trust also comes from saying what does not belong on the platform.</p></div><div className="boundary-list"><article><b>01</b><div><strong>Not a pay-to-earn scheme</strong><p>Workers do not pay an activation fee or unlock earning through a paid tier.</p></div></article><article><b>02</b><div><strong>Not an investment product</strong><p>Erna does not promise returns for depositing money or holding a wallet balance.</p></div></article><article><b>03</b><div><strong>Not a referral chain</strong><p>Referral rewards are single-tier and tied only to a direct referral completing their first approved task.</p></div></article><article><b>04</b><div><strong>Not an airtime or VTU store</strong><p>The platform is focused on performing tasks and advertising tasks.</p></div></article></div></div></section>
    <section className="content-section reporting-section"><div className="page-container reporting-grid"><div className="reporting-mark"><ShieldCheck size={38} /><span>See something wrong?</span></div><div><span className="eyebrow">Speak up early</span><h2>Report suspicious tasks, messages or account activity.</h2><p>Do not complete a task that asks for a password, OTP, card PIN, payment or another person’s identity. Send the task reference to customer care so it can be reviewed.</p><a className="button button-primary" href="/contact">Contact customer care <ArrowRight size={18} /></a></div></div></section>
  </MarketingShell>
}
